// <auto-generated />
using Listless.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listless.Persistence.Migrations
{
    [DbContext(typeof(ListlessContext))]
    [Migration("20240512092814_InitialModels")]
    partial class InitialModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Listless.Persistence.Entities.DbListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("DueBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsStarted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserListId");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("Listless.Persistence.Entities.DbUserList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserLists");
                });

            modelBuilder.Entity("Listless.Persistence.Entities.DbListItem", b =>
                {
                    b.HasOne("Listless.Persistence.Entities.DbUserList", "UserList")
                        .WithMany("Items")
                        .HasForeignKey("UserListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("Listless.Persistence.Entities.DbUserList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
