CREATE TABLE IF NOT EXISTS USER_LISTS(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS LIST_ITEMS(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    IS_COMPLETE INTEGER NOT NULL,
    LIST_ID INTEGER NOT NULL,
    FOREIGN KEY (LIST_ID) REFERENCES USER_LISTS(ID) 
);